filebeat.inputs:
  - type: filestream
    id: docker-logs
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - container: ~
    prospector.scanner.symlinks: true

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      process_array: true
      max_depth: 2
      target: ""
      overwrite_keys: true
  - drop_event:
      when:
        contains:
          container.name: "filebeat"

output.logstash:
  hosts: ["logstash:5044"]
